[build]
  # Directory with the serverless Lambda functions to deploy to AWS.
  publish = "public/"
  functions = "functions/"
  command = "yarn build"

[[redirects]]
  from = "/react-component-testing-book"
  to = "/robust-ui"
  status = 301
  force = true
  
[[plugins]]
  package = "netlify-plugin-gatsby-cache"

# [[plugins]]
#   package = "netlify-plugin-a11y"
#   [plugins.inputs]
#   checkPaths = ['/']
#   # TODO: Turn off warn once errors are resolved
#   resultMode = "warn"
