/post/gatsby-categories /article/gatsby-categories
/post/my-writing-styleguide /article/my-writing-styleguide
/post/css-variables-inheritance-media-queries /article/css-variables-inheritance-media-queries
/post/current-color /article/current-color
/post/magic-numbers-css /article/magic-numbers-css
/post/color-system /article/color-system
/post/elements-that-move-on-hover /article/elements-that-move-on-hover